#import win32con
import re
from BeautifulSoup import BeautifulSoup
import urllib2

url = "http://msdn.microsoft.com/en-us/library/dd375731%28v=vs.85%29.aspx"
pattern = ".*?\<\/dt\>\<dt\>0x([A-Fa-f0-9]{2})h?\<\/dt\>\<\/dl\>\<\/td\>\<td\>\<p\>(.*?)\<\/p\>\<\/td\>"
better_names = [
	('^.*, the \'single-quote/double-quote\' key$', '\''),
	('^.*, the \'(.{1}).*\' key$', '\\1'),
	(' \(.*\)$', ''),
	(' key$', ''),
	('^Numeric keypad', 'NumPad'),
	('^([A-Z\s]*)$', lambda x: ' '.join([y.capitalize() for y in x.group(0).split(' ')])),
	('SHIFT', 'Shift'),
	('CONTROL', 'Control'),
	('MENU', 'Menu'),
	('Ime', 'IME'),
	('^Ins$', 'Insert'),
	('^Del$', 'Delete'),
	('^Ctrl$', 'Control'),
	('\\\\', '\\\\\\\\'), #Replace \ with \\. We have to escape everything twice: once for python, once for regex
	('\'', '\\\''),
	('^ $', 'Space')]
reject = [
	'mouse button',
	'Undefined',
	'Unassigned',
	'Reserved',
	'OEM specific',
	'Used to pass Unicode characters as if they were keystrokes.',
	'Used for miscellaneous characters; it can vary by keyboard.',
	'Either the angle bracket key or the backslash key on the RT 102-key keyboard']



doc = urllib2.urlopen(url).read()
pos1 = doc.find("\n<table>\n")
pos2 = doc.find("\n</table>\n", pos1)
doc = doc[pos1:pos2].replace("\n", "")

output = open('constants.py', 'w')
output.write(
"""### This file has been automatically generated by gen_constants.py

vk_to_string = {
""")

m = re.match(pattern, doc)
while m:
	doc = doc[len(m.group(0)):]
	vk     = int(m.group(1),16)
	string = m.group(2).strip()
	m = re.match(pattern, doc)
	for k, v in better_names:
		string = re.sub(k,v,string)
	
	ok = True
	for r in reject:
		if r in string:
			ok = False
			break
	if not ok: continue
		
	output.write('\t0x%02x:\t\'%s\',\n' % (vk,string))
	

output.write("}")
output.close()
		

"""
virtual_keys = {}
mods = {}
misc = {}
patterns = [
	('^VK_(.*)', virtual_keys),
	('^MOD_(.*)',mods)]

for p in dir(win32con):
	for pattern, save in patterns:
		m = re.match(pattern, p)
		if m:
			save[getattr(win32con, p)] = m.group(1)

for vk, string in virtual_keys:
	
print mods
print win32con.WH_KEYBOARD_LL
print win32con.WM_KEYDOWN"""
